GNN_MSG_KEY = 'm'
GNN_NODE_FEAT_IN_KEY = 'hn_in'
GNN_NODE_FEAT_OUT_KEY = 'hn_out'
GNN_EDGE_FEAT_KEY = 'he'
GNN_EDGE_FEAT_IN_KEY = 'he'
GNN_EDGE_FEAT_OUT_KEY = 'he_out'
GNN_AGG_MSG_KEY = 'h_msg'
GNN_NODE_NORM = 'norm'
GNN_NODE_LABELS_KEY = 'hnl'
GNN_NODE_TYPES_KEY = 'hnt'
GNN_NODE_ATTS_KEY = 'hna'
GNN_EDGE_LABELS_KEY = 'hel'
GNN_EDGE_TYPES_KEY = 'het'
GNN_EDGE_BUFFER_SIZE_KEY = 'hes'
GNN_EDGE_NORM = 'norm'

AIFB = 'aifb'
MUTAG = 'mutag'
MUTAGENICITY = 'mutagenicity'
PTC_FM = 'ptc_fm'
PTC_FR = 'ptc_fr'
PTC_MM = 'ptc_mm'
PTC_MR = 'ptc_mr'


GRAPH = 'graphs'
GNAMES = 'graphs_name'
LABELS = 'labels'
LABELS_TXT = 'labels_txt'
TRAIN_MASK = 'train_mask'
TEST_MASK = 'test_mask'
VAL_MASK = 'val_mask'
N_RELS = 'n_relations' # number of relations
N_CLASSES = 'n_classes' # number of graph classes
FEATURES = 'features'
N_ENTITIES = 'n_entities'
GRAPH_ADJ = 'adj'
MAX_N_NODES = 'max_n_nodes'